# Generated by Django 5.0.4 on 2024-05-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_placed'),
    ]

    operations = [
        migrations.AddField(
            model_name='placed',
            name='department',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
